// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjVUox6eGce62CfWzPpjjQ-pjs89Jg6jA',
    appId: '1:928026776061:web:fc936b8443f32ff51d8994',
    messagingSenderId: '928026776061',
    projectId: 'todo-d9f77',
    authDomain: 'todo-d9f77.firebaseapp.com',
    storageBucket: 'todo-d9f77.firebasestorage.app',
    measurementId: 'G-Z2B79Y3P8P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAto30mzmJAb1Kfl8kcQZFt_M-pVun3zgA',
    appId: '1:928026776061:android:6b048702fb0dd24f1d8994',
    messagingSenderId: '928026776061',
    projectId: 'todo-d9f77',
    storageBucket: 'todo-d9f77.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQW_lcppUry2Oc9hJgrdYI3U_YO5LQPtk',
    appId: '1:928026776061:ios:d7a229d9d6c7b78f1d8994',
    messagingSenderId: '928026776061',
    projectId: 'todo-d9f77',
    storageBucket: 'todo-d9f77.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQW_lcppUry2Oc9hJgrdYI3U_YO5LQPtk',
    appId: '1:928026776061:ios:d7a229d9d6c7b78f1d8994',
    messagingSenderId: '928026776061',
    projectId: 'todo-d9f77',
    storageBucket: 'todo-d9f77.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjVUox6eGce62CfWzPpjjQ-pjs89Jg6jA',
    appId: '1:928026776061:web:5be905f8342e12b41d8994',
    messagingSenderId: '928026776061',
    projectId: 'todo-d9f77',
    authDomain: 'todo-d9f77.firebaseapp.com',
    storageBucket: 'todo-d9f77.firebasestorage.app',
    measurementId: 'G-RTZKZF89FJ',
  );
}
